#
# Copyright 2017 ZTE Corporation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#template: Hello, %s!

#defaultName: ${DW_DEFAULT_NAME:-Stranger}
# the micro service ip
serviceIp:
msbServerAddr: http://127.0.0.1:80

#httpServerAddr: http://127.0.0.1:8201

#parserType: aria

# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080
server:
  type: simple
  rootPath: '/openoapi/policy-lcm/v1/*'
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8269

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: ALL
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    org.openo.policy.lcm.App: INFO
  appenders:
    - type: console
      threshold: INFO
      timeZone: UTC
      logFormat: "%d{yyyy-MM-dd HH:mm:ss SSS} %-5p [%c][%t] - %m%n"
    - type: file
      threshold: INFO
      logFormat: "%d{yyyy-MM-dd HH:mm:ss SSS} %-5p [%c][%t] - %m%n"
      # The file to which current statements will be logged.
      currentLogFilename: ./logs/policy-lcm.log
      # When the log file rotates, the archived log will be renamed to this and gzipped. The
      # %d is replaced with the previous day (yyyy-MM-dd). Custom rolling windows can be created
      # by passing a SimpleDateFormat-compatible format as an argument: "%d{yyyy-MM-dd-hh}".
      archivedLogFilenamePattern: ./logs/policy-lcm-%d{yyyy-MM-dd}.log.gz
      # The number of archived files to keep.
      archivedFileCount: 7
      # The timezone used to format dates. HINT: USE THE DEFAULT, UTC.
      timeZone: UTC

# Timeout in seconds.
timeout: 600
  